### PR TITLE
Release 0.2.3

### PR DESCRIPTION
**Pull request by geoffroyleconte**

### CODE REVIEW

**Comment by AntoninKns** [comment]
Is it possible to change NLPModels v0.19 to [compat] of the Project.toml file ?

**Review by AntoninKns — CHANGES_REQUESTED** [review]
Adding NLPModels 0.19 to [compat] of Project.toml

**Review by AntoninKns — APPROVED** [review]
Thank you very much !

**Comment by tmigot** [comment]
Hi @AntoninKns @geoffroyleconte, Thanks for the PR! It's fine for this one, but note that the CI tests here didn't test NLPModels 0.19 https://github.com/JuliaSmoothOptimizers/SolverCore.jl/runs/6782495966?check_suite_focus=true#step:6:30 because it depends on ADNLPModels which is not yet compatible.

**Pull request merged**
